#!/bin/bash

  # Retrieve script variables
  targetDir=$1
  if [ "$#" -gt 1 ]; then
    tryEnableMPIMerge=$2
  else
    tryEnableMPIMerge=false
  fi

  scriptDir=$(pwd)/$(dirname $0)

  # Setup Extrae for PAPI (or not) 
  papiPath=$(which papi_avail 2> /dev/null)
  if [ -z ${papiPath} ]; then
    # No PAPI available
    papiArg="--without-papi"
  else
    # PAPI available
    papiBaseDir=${papiPath%/bin**}
    papiArg="--with-papi=${papiBaseDir}"
  fi

  # Setup MPI for parallel merge (or not)
  mpiPath=$(which mpirun 2> /dev/null)
  if ! $tryEnableMPIMerge || [ -z ${mpiPath} ]; then
    # No MPI available
    mpiArg="--without-mpi"
  else
    # MPI available detect openmpi or impi
    if [ -z "$I_MPI_ROOT" ]; then
        mpiBaseDir=${mpiPath%/bin**}
        mpiHeaders="--with-mpi-headers=${mpiBaseDir}/include/"
        mpiLib="--with-mpi-libs=${mpiBaseDir}/lib/"
    else
        mpiBaseDir=${I_MPI_ROOT}
        mpiHeaders="${mpiBaseDir}/intel64/include/"
        mpiLib="${mpiBaseDir}/intel64/lib/"
    fi
    # Intel usual folder structure
    # mpiArg="--with-mpi=${mpiBaseDir} --with-mpi-headers=${mpiBaseDir}/intel64/include/ --with-mpi-libs=${mpiBaseDir}/intel64/lib/release/ --enable-parallel-merge"
    # Openmpi usual folder structure
    # mpiArg="--with-mpi=${mpiBaseDir} --with-mpi-headers=${mpiHeaders} --with-mpi-libs=${mpiLib} --enable-parallel-merge"
    mpiBaseDir="/home/software/openmpi/1.10.7-GNU"
    mpiArg="--with-mpi=${mpiBaseDir} --with-mpi-headers=${mpiBaseDir}/include/ --with-mpi-libs=${mpiBaseDir}/lib/ --enable-parallel-merge"
  fi

  # Create installation folder
  mkdir -p ${targetDir}

  # Configure, compile and install
  autoreconf --force --install
  if [ $? -ne 0 ]; then
    exit 1
  fi

  ./configure --enable-gettimeofday-clock \
              --without-unwind \
              --without-dyninst \
              --without-binutils \
              ${mpiArg} \
              ${papiArg} \
              --with-java-jdk=${JAVA_HOME} \
              --disable-openmp \
              --enable-nanos \
              --disable-smpss \
              --disable-instrument-io \
              --prefix=${targetDir} \
              --libdir=${targetDir}/lib
  if [ $? -ne 0 ]; then
    exit 1
  fi

  make clean install
  if [ $? -ne 0 ]; then
    exit 1
  fi  

  # Exit normal
  exit 0

